#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir, platform } from 'node:os';
import { spawn } from 'node:child_process';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const configPath = resolve(root, 'wadi-server.json');
const config = existsSync(configPath) ? JSON.parse(readFileSync(configPath, 'utf8')) : {};
const base = platform() === 'win32' ? resolve(process.env.LOCALAPPDATA || homedir(), 'Wadi') : platform() === 'darwin' ? resolve(homedir(), 'Library/Application Support/Wadi') : resolve(process.env.XDG_DATA_HOME || resolve(homedir(), '.local/share'), 'wadi');
const data = resolve(process.env.WADI_DATA_DIR || config.dataDirectory || base);
mkdirSync(data, { recursive: true });
const frontend = resolve(root, 'apps/frontend');
const standalone = resolve(frontend, '.next/standalone');
const entry = existsSync(resolve(standalone, 'apps/frontend/server.js')) ? resolve(standalone, 'apps/frontend/server.js') : resolve(standalone, 'server.js');
if (!existsSync(entry)) throw new Error('Build Wadi first: pnpm build && pnpm package:server');
const port = String(process.env.PORT || config.port || 5173);
const env = { ...process.env, NODE_ENV: 'production', HOSTNAME: process.env.WADI_HOST || config.host || '0.0.0.0', PORT: port, WADI_DATA_DIR: data, DATABASE_URL: process.env.DATABASE_URL || resolve(data, 'wadi.sqlite'), WADI_ENABLE_CONVERSION: process.env.WADI_ENABLE_CONVERSION ?? (config.conversion === true ? '1' : '0') };
console.log(`Wadi: http://localhost:${port} | Data: ${data} | Conversion: ${env.WADI_ENABLE_CONVERSION === '1' ? 'on' : 'off'}`);
const child = spawn(process.execPath, [entry], { cwd: dirname(entry), env, stdio: 'inherit' });
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => child.kill(signal));
child.on('error', error => { console.error(error.message); process.exitCode = 1; });
child.on('exit', code => { process.exitCode = code ?? 0; });
