import { LegalPage } from '@/components/legal-page'
export default function Privacy() {
  return <LegalPage title="Privacy policy">
    <p>Daniel Westbrook operates Wadi and is responsible for the account information described here. For privacy questions, access requests, corrections, or complaints, contact <a href="mailto:westy12dan@gmail.com">westy12dan@gmail.com</a>. Please do not post passwords, private add-on URLs, or account exports in public GitHub issues.</p>
    <h2>What Wadi stores</h2>
    <p>Wadi stores your email, a cryptographic password hash, account and profile details, active sessions, installed add-ons and their configuration, lists, watch progress and history, playback settings, and preferences needed to sync your library. Add-on configuration and saved stream URLs may contain access keys or other private information. Wadi does not store your password in readable form.</p>
    <p>Your browser stores a session token and device preferences, including appearance and TV navigation. The desktop app stores its session encrypted using the operating system’s credential protection, along with local preferences and temporary media files used for playback. Logging out removes the active app session; deleting your hosted account does not automatically erase files or exports from your devices.</p>
    <h2>Why this information is used</h2>
    <p>Wadi uses this information to authenticate you, provide profiles and playback, sync your library, maintain security, and respond to support or legal requests. Where a legal basis is required, this processing supports providing the service you request, legitimate interests in security and maintenance, and applicable legal obligations. Wadi does not sell your account information or use it for advertising profiles.</p>
    <h2>Who receives information</h2>
    <p>Resend delivers verification emails and processes your email address, message content, and delivery status. Wadi temporarily stores pending registration details and hashed verification codes, and limits attempts and email requests to prevent abuse. Codes expire after 15 minutes. Expired verification records and hashed network rate-limit records are removed during subsequent verification requests.</p>
    <p>The hosted web app and API are designed to run on Vercel with a PostgreSQL database on Railway. Hosting operators may process connection details, IP addresses, request timestamps, and operational logs as part of delivering and securing the service. Actual storage locations depend on the deployment and provider configuration and may be outside your country. A self-hosted installation uses the infrastructure selected by its operator.</p>
    <p>Add-ons receive requests needed to browse catalogues, search, and resolve streams, including relevant content identifiers, search terms, and any configuration you supply. Web requests sent through Wadi’s API reach add-ons from the server. Media, images, subtitles and other resources may be requested directly by your browser or desktop app, revealing your IP address to their providers. External players, GitHub downloads, and Google Cast have their own privacy practices. The web app loads Google’s Cast support script. Wadi cannot control how these third parties handle information.</p>
    <p>For supported titles in the built-in player, Wadi’s API sends the IMDb title identifier and episode numbers (or a movie indicator) to IntroDB to retrieve intro, recap and outro timestamps. These requests come from the server and do not include your account credentials or stream URLs.</p>
    <h2>Retention and your choices</h2>
    <p>Account records remain while your account exists. Account deletion removes your account and associated profiles, lists, add-ons, watch records, settings, and sessions from the active database. Copies may remain in infrastructure backups or operational logs until those systems’ retention periods expire, or where required by law. Wadi does not promise immediate erasure from third-party systems.</p>
    <p>Account settings lets you export your stored account data, change your password, and delete your account. Exports exclude password hashes and session credentials but include your private add-on configuration. Keep them secure. You can also remove local browser data or uninstall the desktop app; these actions alone do not delete your hosted account.</p>
    <p>Depending on your location, you may have rights to access, correct, erase, restrict or object to processing of your information, receive a portable copy, and complain to a relevant privacy regulator. Contact the email above for requests the app cannot handle. We may need to verify your identity before acting.</p>
    <h2>Security and updates</h2>
    <p>Wadi uses hashed passwords, authenticated account access, and operating-system encryption for desktop sessions. No system can guarantee complete security. This policy will be updated as Wadi’s features or data handling change, with the revision date shown above.</p>
  </LegalPage>
}
