import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { hash } from '@node-rs/argon2';
import { createApp } from './main.js';
import { testDatabase } from './test-database.js';
test('verification gates registration and existing accounts; expires, throttles, and consumes codes once', async t => {
  const mail=[];
  const {app,db}=createApp({database:await testDatabase(t),sendVerificationEmail:async value=>mail.push(value)});
  const server=app.listen(0,'127.0.0.1'); await new Promise(r=>server.once('listening',r));
  t.after(async()=>{server.closeAllConnections();server.close();await db.close();});
  const request=async(path,body)=>{const r=await fetch(`http://127.0.0.1:${server.address().port}/api/auth/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,body:await r.json()};};
  const credentials={email:'verify@example.com',password:'test-password'};
  const pending=await request('register',credentials);assert.equal(pending.status,202);assert.equal(pending.body.token,undefined);
  assert.equal((await db.all('SELECT id FROM users')).length,0);
  assert.equal((await request('register',credentials)).status,429);
  const wrong=mail[0].code==='00000000'?'11111111':'00000000';
  assert.equal((await request('verify-email',{challenge:pending.body.challenge,code:wrong})).status,400);
  const verified=await request('verify-email',{challenge:pending.body.challenge,code:mail[0].code});assert.equal(verified.status,200);assert.ok(verified.body.token);
  assert.equal((await request('verify-email',{challenge:pending.body.challenge,code:mail[0].code})).status,400);
  assert.equal((await request('login',credentials)).status,200);
  const limited=await request('register',{...credentials,email:'attempts@example.com'});
  const real=mail.at(-1).code, bad=real==='00000000'?'11111111':'00000000';
  for(let i=0;i<5;i++)assert.equal((await request('verify-email',{challenge:limited.body.challenge,code:bad})).status,400);
  assert.equal((await request('verify-email',{challenge:limited.body.challenge,code:real})).status,400);
  const expired=await request('register',{...credentials,email:'expired@example.com'});
  await db.run('UPDATE email_verifications SET expires_at=? WHERE email=?',new Date(0).toISOString(),'expired@example.com');
  assert.equal((await request('verify-email',{challenge:expired.body.challenge,code:mail.at(-1).code})).status,400);
  await db.run('INSERT INTO users(id,email,password_hash) VALUES(?,?,?)',randomUUID(),'existing@example.com',await hash(credentials.password));
  const existing=await request('login',{...credentials,email:'existing@example.com'});assert.equal(existing.status,202);assert.equal(existing.body.token,undefined);
  assert.equal((await request('verify-email',{challenge:existing.body.challenge,code:mail.at(-1).code})).status,200);
});
